src/Entity/Todo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TodoRepository")
 */
class Todo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_done;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $done_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsDone(): ?bool
    {
        return $this->is_done;
    }

    public function setIsDone(?bool $is_done): self
    {
        $this->is_done = $is_done;

        return $this;
    }

    public function getDoneAt(): ?\DateTimeInterface
    {
        return $this->done_at;
    }

    public function setDoneAt(?\DateTimeInterface $done_at): self
    {
        $this->done_at = $done_at;

        return $this;
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;


use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\TodoRepository;

class TodoController extends AbstractController
{
    /** 
     * @Route("/todo", name="todo")
    */
    public function index(TodoRepository $repository)
    {
        return $this->render('todo/list.html.twig',[
            'todos'=>$repository->findAll(),
        ]);
    } 


}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/todo/list.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Todo list</title>
    </head>
    <body>
        <h1>Todo list</h1>
        <table>
            <thead>
                <tr>
                    <td>No.</td>
                    <td>Todo</td>
                    <td>Status</td>
                    <td>Pilihan</td>
                </tr>
            </thead>
            <tbody>
                {% for i, data in todos %}
                <tr>
                    <td>{{ i+1 }}</td>
                    <td>{{data.description}}</td>
                    <td>
                        {%  if data.isDone %}
                            {{ 'SELESAI(' ~ (data.doneAt | date('d-m-Y H:i:s')) ~')'}}
                        {% else %}
                            {{ 'BELUM SELESAI' }}
                        {% endif %}
                    </td>
                    <td>
                        <a href="#">Edit</a>
                        <a href="#">Hapus</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <a href="#">Tambah Baru</a>
    </body>
</html>